name: plants_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  number_paginator: ^0.4.0
  riverpod_annotation: ^2.3.0
  equatable: ^2.0.5
  auto_route: ^7.8.4
  get_it: ^7.7.0

  flutter_rating_bar: ^4.0.1
  like_button: ^2.0.5
  simple_tags: ^0.0.6
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.2
  flutter_typeahead: ^5.2.0
  flutter_secure_storage: ^4.2.1
  another_flushbar: ^1.12.30
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  email_validator: ^2.1.17
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  flutter_spinkit: ^5.2.1
  multi_image_picker_view: ^1.0.3
  connectivity_plus: ^6.0.3
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.0.6
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl_phone_number_input: ^0.7.4
  custom_radio_grouped_button: ^2.2.1







dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2

  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3



flutter_native_splash:
  color: "#ffffff"
  image: assets/brand_logo.png
  android: true

flutter_launcher_icons:
  color: "#ffffff"
  android: true
  image_path:  "assets/brand_logo.png"

flutter:
  uses-material-design: true



  assets:
    - .env
    - assets/brand_logo.png
    - assets/empty_list_icon.png
    - assets/water_drops.png
    - assets/error_icon.jpg
    - assets/audio/water-drip.mp3
    - assets/onboarding/onboarding1.png
    - assets/onboarding/onboarding2.png
    - assets/onboarding/onboarding3.png
    - assets/category/test_icon.png
